### ISSUE TITLE
Teacher/Student Syncfusion controls sample for Class work Time entry sample

### ISSUE THREAD

**Issue by papyr** [syncfusion/ej2-aspnetcore-samples#18]
Hello can you add a Syncfusion control sample for teachers and students recording class work and projects time on a weekly basis with their hours and projects

- [ ] `Which Syncfusion controls, and how to calculate totals, prevent errors`.
- [ ] Save this with a VM to the backend using Syncfusion Tag Helpers
- [ ] How to make this so the whole page does not refresh and it saves each cell automatically to backend
- [ ] Student or teach can pick HomeWork Project, Phase and Activity. (to prevent errors for students, if a _previous combination was previously selected_ then it should _not be available in the next row_)
- [ ] Totals should have rules, where each day cannot exceed 24 hrs, and weekend day cannot exceet 4 hrs
- [ ] the cells should only accept time 1 hr, 30 mins etc, this should be configurable, and it should show totals

![image](https://user-images.githubusercontent.com/12733414/110808280-d4422a80-8251-11eb-8103-347be8616090.png)

**Comment by ghost** [comment]
Hi @papyr,

Sorry for the delay in updating the response.

Based on your queries, we suggest you to use the EJ2 Grid control to achieve your requirement. Please find the response for the queries addressed based on the EJ2 Grid control below,

_**Query – 1: “Which Syncfusion controls, and how to calculate totals, prevent errors.”**_

Based on this query we suspect that your requirement is to display total values for certain columns. For this you can use the Grid’s aggregate functionality to achieve your requirement. More details on this with online demo sample can be checked in the below links,

**Documentation:** https://ej2.syncfusion.com/aspnetcore/documentation/grid/aggregates/

**Online demo sample:** https://ej2.syncfusion.com/aspnetcore/Grid/DefaultAggregate#/bootstrap5

_**Query – 2: “Save this with a VM to the backend using Syncfusion Tag Helpers”**_

The EJ2 Grid supports the following adaptors to communicate with the data source in the back-end – Json, URL, OData, ODataV4, Remote Save, Web API and WebMethod adaptor. Each adaptor uses a different way to send and receive requests and response from remote services. They are explained in the below documentation link which you can check for more details,

**Documentation:** https://ej2.syncfusion.com/aspnetcore/documentation/grid/data-binding/#remote-data
                              https://ej2.syncfusion.com/aspnetcore/documentation/grid/edit/#url-adaptor

Please check the below online remote data binding sample for reference,

**Online demo sample:** https://ej2.syncfusion.com/aspnetcore/Grid/RemoteData#/bootstrap5

You can use the adaptor which best suits your requirement for binding data and performing grid actions(CRUD, Sort, Page, Filter, etc. ) from the backend.

_**Query – 3: “How to make this so the whole page does not refresh and it saves each cell automatically to backend”**_

By default when updating the cell values in Grid only the current edited row value will be sent to the back end and it will not cause the whole Grid to refresh. This is the default behavior of Grid’s editing functionality and you can check this case in the below online editing sample link for reference where local data is use,

**Online demo sample:** https://ej2.syncfusion.com/aspnetcore/Grid/InlineEditing#/bootstrap5

_**Query – 4: “Student or teach can pick HomeWork Project, Phase and Activity. (to prevent errors for students, if a previous combination was previously selected then it should not be available in the next row)”**_

Based on this query and the shared image we could see that edit controls are enabled in all the table rows, but in the EJ2 Grid only one row/cell can be edited at a time. This is the default behavior of Grid’s editing functionality(can be checked for reference from the above shared demo link). So please elaborate on your exact requirement with more details to validate further.

_**Query – 5: “Totals should have rules, where each day cannot exceed 24 hrs, and weekend day cannot exceet 4 hrs”**_

From this query we are not clear if your requirement is to calculate total for each row or each column. So please elaborate on your exact requirement in this query with more details to validate further.

_**Query – 6: “the cells should only accept time 1 hr, 30 mins etc, this should be configurable, and it should show totals”**_

Since this query is dependent on query – 4, we will provide the further details for this requirement based on your update for that query.

Regards,
Sujith R

**Comment by papyr** [comment]
this leaves a lot for the developer to figure out, I thought the sample would address this which is the point of having a 3rd party control
