### ISSUE TITLE
Project missing .sln file

### ISSUE THREAD

**Issue by imnkk** [syncfusion/ej2-aspnetcore-samples#8]
Hi,

The project is missing .sln(Solution) file. Could you please update the project with the sln file because by opening it with .csproj it's throwing error & Re-Build project is also not resolving that issue. I need to learn - How to work on it? Could you please help me?

Thanks in advance.

**Comment by gurunathancs1991** [comment]
Hi @imnkk ,
 
Thanks for contacting Syncfusion.
 
Yes, we can able to replicate your reported error when opening the .csproj file form our Github link. Since this .csproj is outdated file with previous version, these error occurs, so we will update this to newer versions samples in GitHub by 11th October, 2019 . Also the sln file is not needed if we update this .csproj file.
 
Feedback link for tracking: https://www.syncfusion.com/feedback/9325/need-to-update-the-asp-net-core-github-samples
 
Reference link: https://bytes.com/topic/c-sharp/answers/247242-difference-between-csproj-sln
 
In order to work on your EJ2 ASP.NET core projects please find the below getting started link and SB link for more references
 
https://ej2.syncfusion.com/aspnetcore/documentation/introduction/
https://ej2.syncfusion.com/aspnetcore/Grid/GridOverview#/material
 
Please let us know if any concerns. 
 
Regards,
Gurunathan

**Comment by gurunathancs1991** [comment]
Hi @imnkk ,

We have resolved the reported issue and refreshed the project. can you please ensure it in your end ?

Regards,
Gurunathan
